version: '3.7'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=mysql://user:password@mysql/previsao_tempo_db
      - FLASK_APP=app
      - FLASK_ENV=development
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - "3308:3308"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: previsao_tempo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: